name: CommandCode
version: "1.5"
author: Bodyash
main: me.bodyash.commandcode.Main
commands:
    generateCode:
        description: Allows you to generate a code for a specific goody.
        permissions: commandcode.generatecode
        default: op
    redeemCode:
        description: Allows you to redeem a specific code and gives you the goods.
        permissions: commandcode.redeem
        default: op
    deleteCode:
        description: Allows you to remove a specific code.
        permissions: commandcode.deletecode
        default: op
    code:
        description: Allows you to use /code command (add, delete or reedeem)